export type SessionResultsPosition = {
  Position: number;
  ClassPosition: number;
  CarIdx: number;
  Lap: number;
  Time: number;
  FastestLap: number;
  FastestTime: number;
  LastTime: number;
  LapsLed: number;
  LapsComplete: number;
  JokerLapsComplete: number;
  LapsDriven: number;
  Incidents: number;
  ReasonOutId: number;
  ReasonOutStr: string;
};

export type SessionResultsFastestLap = {
  CarIdx: number;
  FastestLap: number;
  FastestTime: number;
};

export type Session = {
  SessionNum: number;
  SessionLaps: string;
  SessionTime: string;
  SessionNumLapsToAvg: number;
  SessionType: string;
  SessionTrackRubberState: string;
  SessionName: string;
  SessionSubType: string | null;
  SessionSkipped: number;
  SessionRunGroupsUsed: number;
  SessionEnforceTireCompoundChange: number;
  ResultsPositions: SessionResultsPosition[];
  ResultsFastestLap: SessionResultsFastestLap[];
  ResultsAverageLapTime: number;
  ResultsNumCautionFlags: number;
  ResultsNumCautionLaps: number;
  ResultsNumLeadChanges: number;
  ResultsLapsComplete: number;
  ResultsOfficial: number;
};

export type SessionInfo = {
  CurrentSessionNum: number;
  Sessions: Session[];
};

export type DriverTire = {
  TireIndex: number;
  TireCompoundType: string;
};

export type Driver = {
  CarIdx: number;
  UserName: string;
  AbbrevName: string;
  Initials: string;
  UserID: number;
  TeamID: number;
  TeamName: string;
  CarNumber: string;
  CarNumberRaw: number;
  CarPath: string;
  CarClassID: number;
  CarID: number;
  CarIsPaceCar: number;
  CarIsAI: number;
  CarIsElectric: number;
  CarScreenName: string;
  CarScreenNameShort: string;
  CarCfg: number;
  CarCfgName: string | null;
  CarCfgCustomPaintExt: string | null;
  CarClassShortName: string | null;
  CarClassRelSpeed: number;
  CarClassLicenseLevel: number;
  CarClassMaxFuelPct: string;
  CarClassWeightPenalty: string;
  CarClassPowerAdjust: string;
  CarClassDryTireSetLimit: string;
  CarClassColor: number;
  CarClassEstLapTime: number;
  IRating: number;
  LicLevel: number;
  LicSubLevel: number;
  LicString: string;
  LicColor: string;
  IsSpectator: number;
  CarDesignStr: string;
  HelmetDesignStr: string;
  SuitDesignStr: string;
  BodyType: number;
  FaceType: number;
  HelmetType: number;
  CarNumberDesignStr: string;
  CarSponsor_1: number;
  CarSponsor_2: number;
  CurDriverIncidentCount: number;
  TeamIncidentCount: number;
};

export type WeekendOptions = {
  NumStarters: number;
  StartingGrid: string;
  QualifyScoring: string;
  CourseCautions: string;
  StandingStart: number;
  ShortParadeLap: number;
  Restarts: string;
  WeatherType: string;
  Skies: string;
  WindDirection: string;
  WindSpeed: string;
  WeatherTemp: string;
  RelativeHumidity: string;
  FogLevel: string;
  TimeOfDay: string;
  Date: string;
  EarthRotationSpeedupFactor: number;
  Unofficial: number;
  CommercialMode: string;
  NightMode: string;
  IsFixedSetup: number;
  StrictLapsChecking: string;
  HasOpenRegistration: number;
  HardcoreLevel: number;
  NumJokerLaps: number;
  IncidentLimit: string;
  IncidentWarningInitialLimit: string;
  IncidentWarningSubsequentLimit: string;
  FastRepairsLimit: string;
  GreenWhiteCheckeredLimit: number;
};

export type TelemetryOptions = {
  TelemetryDiskFile: string;
};

export type WeekendInfo = {
  TrackName: string;
  TrackID: number;
  TrackLength: string;
  TrackLengthOfficial: string;
  TrackDisplayName: string;
  TrackDisplayShortName: string;
  TrackConfigName: string;
  TrackCity: string;
  TrackState: string;
  TrackCountry: string;
  TrackAltitude: string;
  TrackLatitude: string;
  TrackLongitude: string;
  TrackNorthOffset: string;
  TrackNumTurns: number;
  TrackPitSpeedLimit: string;
  TrackPaceSpeed: string;
  TrackNumPitStalls: number;
  TrackType: string;
  TrackDirection: string;
  TrackWeatherType: string;
  TrackSkies: string;
  TrackSurfaceTemp: string;
  TrackSurfaceTempCrew: string;
  TrackAirTemp: string;
  TrackAirPressure: string;
  TrackAirDensity: string;
  TrackWindVel: string;
  TrackWindDir: string;
  TrackRelativeHumidity: string;
  TrackFogLevel: string;
  TrackPrecipitation: string;
  TrackCleanup: number;
  TrackDynamicTrack: number;
  TrackVersion: string;
  SeriesID: number;
  SeasonID: number;
  SessionID: number;
  SubSessionID: number;
  LeagueID: number;
  Official: number;
  RaceWeek: number;
  EventType: string;
  Category: string;
  SimMode: string;
  TeamRacing: number;
  MinDrivers: number;
  MaxDrivers: number;
  DCRuleSet: string;
  QualifierMustStartRace: number;
  NumCarClasses: number;
  NumCarTypes: number;
  HeatRacing: number;
  BuildType: string;
  BuildTarget: string;
  BuildVersion: string;
  RaceFarm: string | null;
  WeekendOptions: WeekendOptions;
  TelemetryOptions: TelemetryOptions;
};

export type DriverInfo = {
  DriverCarIdx: number;
  DriverUserID: number;
  PaceCarIdx: number;
  DriverIsAdmin: number;
  DriverHeadPosX: number;
  DriverHeadPosY: number;
  DriverHeadPosZ: number;
  DriverCarIsElectric: number;
  DriverCarIdleRPM: number;
  DriverCarRedLine: number;
  DriverCarEngCylinderCount: number;
  DriverCarFuelKgPerLtr: number;
  DriverCarFuelMaxLtr: number;
  DriverCarMaxFuelPct: number;
  DriverCarGearNumForward: number;
  DriverCarGearNeutral: number;
  DriverCarGearReverse: number;
  DriverGearboxType: string;
  DriverGearboxControlType: string;
  DriverCarShiftAid: string;
  DriverCarSLFirstRPM: number;
  DriverCarSLShiftRPM: number;
  DriverCarSLLastRPM: number;
  DriverCarSLBlinkRPM: number;
  DriverCarVersion: string;
  DriverPitTrkPct: number;
  DriverCarEstLapTime: number;
  DriverSetupName: string;
  DriverSetupIsModified: number;
  DriverSetupLoadTypeName: string;
  DriverSetupPassedTech: number;
  DriverIncidentCount: number;
  DriverBrakeCurvingFactor: number;
  DriverTires: DriverTire[];
  Drivers: Driver[];
};
